builds:
  - env: [CGO_ENABLED=0]
    goos:
      - freebsd
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: tgz
    name_template: '{{ .ProjectName }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}'
changelog:
  use: github-native