version: 2
project_name: helm-schema-gen
builds:
  - id: default
    main: .
    binary: bin/schema-gen
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -X github.com/rhoat/helm-schema-gen/pkg/commands/version.Version={{ .Env.VERSION }}
    goos:
      - freebsd
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: default
    builds:
    - default
    format: tgz
    name_template: '{{ .ProjectName }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}'
    wrap_in_directory: schema-gen
    files:
    - README.md
    - plugin.yaml
    - LICENSE
changelog:
  use: github-native
release:
  prerelease: auto