name: "schema-gen"
version: "0.0.11"
usage: "generate json schema for values yaml"
description: "generate json schema for values yaml"
command: "$HELM_PLUGIN_DIR/bin/schema-gen"
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/scripts/install-binary.sh -u"
