name: govulncheck

on:
  pull_request:

permissions:
  contents: write

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-file: go.mod
           go-package: ./...
